/**
 * JS Tag v3.4.3 (Tue Feb 25 15:32:44 UTC 2020)
 * RevJet
 * http://www.revjet.com/
 */
(function(){var g,h="function"==typeof Object.create?Object.create:function(a){function c(){}c.prototype=a;return new c},l;if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var n;a:{var p={V:!0},q={};try{q.__proto__=p;n=q.V;break a}catch(a){}n=!1}l=n?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null}var r=l;function t(a,c,b){if("string"==typeof c)a.style[c]=b;else for(var d in c)a.style[d]=c[d]};function u(a){try{window.document.write(a)}catch(c){}}function v(a,c,b){b=void 0===b?window.document:b;a=b.createElement(a);for(var d in c.o)c.o.hasOwnProperty(d)&&a.setAttribute(d,c.o[d]);for(var e in c.style)c.style.hasOwnProperty(e)&&(a.style[e]=c.style[e]);return a}function w(a){var c={margin:0,padding:0,position:"relative",left:0,top:0,opacity:1,visibility:"visible",overflow:"hidden",border:"none",cssFloat:"none"};if(a)for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}
function x(a){var c={allowtransparency:"false",frameborder:"0",hspace:"0",marginwidth:"0",marginheight:"0",scrolling:"no",vspace:"0"};if(a)for(var b in a)a.hasOwnProperty(b)&&(c[b]=a[b]);return c}function y(a){a&&a.parentNode&&a.parentNode.removeChild(a)};function z(a,c,b){"undefined"!==typeof window.addEventListener?a.addEventListener(c,b,!1):a.attachEvent("on"+c,b)}function A(a,c,b){"undefined"!==typeof window.removeEventListener?a.removeEventListener(c,b,!1):a.detachEvent("on"+c,b)};function B(a){return a.replace(/<script[^>]*/ig,function(a){return a.replace(/(\s+)(type)(\s*=\s*)/ig,"$1data-revjet-script-type$3").replace(/(\s+)(language)(\s*=\s*)/ig,"$1data-revjet-script-language$3").replace(/(\s+)(src)(\s*=\s*)/ig,"$1data-revjet-script-src$3")+' type="text/revjet"'})}function C(a,c){var b=c.bind(this);a.addEventListener?a.addEventListener("load",b,!1):a.onreadystatechange=function(){if("loaded"===a.readyState||"complete"===a.readyState)a.onreadystatechange=null,b()}}
function D(a,c,b,d){return function(){if(0===c.length)d&&d();else{var e=c.shift(),f=D(a,c,b,d);if("SCRIPT"===e.nodeName&&"text/revjet"===e.type){var k=b.createElement("script");k.async=!1;var m=e.getAttribute("data-revjet-script-type");m&&(k.type=m);k.id=e.id;k.text=e.text||e.textContent||e.innerHTML||"";(m=e.getAttribute("data-revjet-script-language"))&&k.setAttribute("language",m);e.charset&&(k.charset=e.charset);if(e=e.getAttribute("data-revjet-script-src"))k.src=e;k.src&&C(k,f);a.insertBefore(k,
null);k.src||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));a.insertBefore(e,null);D(e,k,b,f)()}else a.insertBefore(e,null),f()}}};var E="undefined"!==typeof window.postMessage,F="undefined"!==typeof window.JSON&&"function"===typeof window.JSON.parse,G="undefined"!==typeof window?window:{};function H(a){a=a.split(".");for(var c=G,b;b=a.shift();)if(null!=c[b])c=c[b];else return null;return c};var I=null;function aa(){this.c=H("extern")||H("$sf.ext");this.a=!1;this.f=[]}function ba(a,c,b){if(a.c&&!a.a)try{$sf.ext.register(c,b,function(b,c){for(var d=a.f,e=0;e<d.length;e++)d[e](b,c)}),a.a=!0}catch(d){}};function J(a,c){this.g=a;this.a={};this.c=this.f=null;this.i=[];this.j=[];this.m=[];if(c&&c.c&&!this.f){var b=this.g.document.getElementById("REVJET_Tag-MESSAGING_FRAME");b?this.f=b:(this.f=v("iframe",{o:x({id:"REVJET_Tag-MESSAGING_FRAME"}),style:w({display:"none"})}),this.g.document.body.appendChild(this.f))}}
J.prototype.s=function(a,c,b){if(a.initialized){for(a=this.j.length-1;0<=a;a--)c=this.j[a],c.target===b&&(c.target.postMessage(JSON.stringify(c.message),"*"),this.j.splice(a,1));a:{for(a=0;a<this.i.length;a++)if(this.i[a]===b){a=!0;break a}a=!1}if(!a)for(this.i.push(b),a=this.m.length-1;0<=a;a--)c=this.m[a],c.da===b&&c.code()}};
function ca(a,c){a.c||(a.c=function(b){if(b&&"data"in b){var d=null;try{d=JSON.parse(b.data)}catch(f){}if(d&&"module"in d&&d.method&&"REVJET_Tag.Ad"===d.module){var e=c[d.method];e&&e.call(a,d.properties,d.messageId,b.source)}}},z(a.f?a.f.contentWindow:a.g,"message",a.c))}function K(a){a.c&&(A(a.g,"message",a.c),a.c=null)};var L=0;
function M(a,c,b){b=void 0===b?!1:b;var d=a.getSlotResponseObject();this.U=!!window.inDapIF;this.c=a;var e=window.parent;if(this.U&&window!==e){var f=this.c.getSlotObjectName();e[f]?L=++e[f].instanceNumber:(e[f]={},e[f].instanceNumber=++L)}else L++;this.R=c;this.P=d.content||"";this.N=d.failover_query_string;this.O=d.failover_url;this.m=a.getAdWidth();this.s=a.getAdHeight();this.L=!1;this.i=window;I||(I=new aa);this.I=I;ba(this.I,this.m,this.s);if(this.f=b?null:new J(this.i,this.I))this.f.a.close=this.Y.bind(this),
this.f.a.collapse=this.Z.bind(this),this.f.a.expand=this.$.bind(this),this.f.a.relayAction=this.ba.bind(this),this.f.a.reload=this.ca.bind(this),this.f.a.refresh=this.aa.bind(this)}g=M.prototype;g.Y=function(a,c,b){this.F(b)&&this.c.destroy()};g.$=function(){};g.Z=function(){};g.ba=function(){};g.ca=function(a,c,b){this.F(b)&&this.c.reload()};g.aa=function(a,c,b){this.F(b)&&this.c.refresh()};g.F=function(){return!1};g.X=function(){return this.R};
function N(a){var c=a.N;if(a.O||c){c=a.O;var b=a.N;if(c){b=a.c;var d=b.getAdapter();c="https://"+b.getAdsDomainName()+(d?"/"+d:"")+c}else c=b?(-1!==b.toString().indexOf("msgCode=1005")?O(a,"/~cdn/Ads/ad_shared/static/406.html"):O(a,"/~cdn/Ads/ad_shared/static/failover.html"))+"?"+b:null;if(c)return'<!DOCTYPE html>\n<html>\n<head>\n<style type="text/css">* {padding:0;margin:0;}</style>\n</head>\n<body style="background-color: #fff;">\n<iframe '+['src="'+c+'"','allowtransparency="false" frameborder="0" marginwidth="0" marginheight="0" scrolling="no"',
'width="'+a.m+'"','height="'+a.s+'"','style="border:0;vertical-align:bottom;width:'+a.m+"px;height:"+a.s+'px;"'].join(" ")+"></iframe>\n</body>\n</html>"}return a.P}g.G=function(){if(this.f){var a=this.f;E&&F&&(a.a.setElementsInitialized=a.s.bind(a),ca(a,a.a))}window.context&&window.context.reportRenderedEntityIdentifier&&window.context.reportRenderedEntityIdentifier(da(this))};g.D=function(){this.f&&K(this.f)};g.C=function(){this.L=!0;if(this.f){var a=this.f;K(a);a.j=[];a.m=[];a.i=[]}this.I.f=[]};
g.J=function(){return[]};g.W=function(){return this.L};function O(a,c){var b=a.c,d=b.getAdapter();return"https://"+b.getCdnDomainName()+(d?"/"+d:"")+c}function da(a){if(a=N(a)){var c=/<title>([0-9]+)\/[0-9]+<\/title>/gi.exec(a);return c&&0<c.length?"revjet-"+c[1]:"revjet-S"+a.length}return"revjet-S0"}function P(a){a=a.c;a=a.getOptions?a.getOptions():{};var c="{}";try{c=JSON.stringify(a)}catch(b){}return c}M.prototype.adDestroyed=M.prototype.W;M.prototype.getFrames=M.prototype.J;
M.prototype.destroyAd=M.prototype.C;M.prototype.hideAd=M.prototype.D;M.prototype.showAd=M.prototype.G;M.prototype.getAdType=M.prototype.X;var ea=/<\/body>\s*<\/html>/i;function Q(a,c,b){M.call(this,a,c,b);a=a.getSlotResponseObject();this.M=a.embd_tag_id;this.T=a.disable_iframe;this.S=a.deliveryWrapper;this.H=!!a.autoscale;this.B=this.j=this.g=this.a=null;this.K=!!a.close_button;this.A=this.v=this.u=null}Q.prototype=h(M.prototype);Q.prototype.constructor=Q;if(r)r(Q,M);else for(var R in M)if("prototype"!=R)if(Object.defineProperties){var S=Object.getOwnPropertyDescriptor(M,R);S&&Object.defineProperty(Q,R,S)}else Q[R]=M[R];Q.a=M.prototype;
function T(a,c){try{var b=a.contentDocument||a.contentWindow.document;b.open();b.write(c);b.close()}catch(d){}}function U(a,c){var b=c/a.m;return{scale:b.toFixed(4),height:Math.round(a.s*b)}}
function V(a,c){if(c){var b=a.g;if(b)return b.getBoundingClientRect().width}else{var d=W(a);if(d)return b=a.i.document.createElement("div"),b.style.cssText="position:relative;left:0;top:0;right:auto;bottom:auto;width:100%;border:none;padding:0;margin:0;visibility:hidden;",d.appendChild(b),d=b.getBoundingClientRect().width,b.parentNode.removeChild(b),d}return 0}
function fa(a){function c(){var b=V(a,!0);b=U(a,b);var c=a.g;c&&t(c,"height",b.height+"px");(c=a.j)&&t(c,"height",b.height+"px");if(c=a.a)b="scale("+b.scale+")",c.style.webkitTransform=b,c.style.transform=b}var b=a.i;b.requestAnimationFrame?b.requestAnimationFrame(function(){return c()}):b.setTimeout(function(){return c()},16)}function X(a){a=x({width:a.m,height:a.s,name:"revjet-single-iframe","data-revjet-options":P(a)});return v("iframe",{o:a,style:w()})}
function ha(a){if(!/loaded|complete/.test(window.document.readyState)){var c=a.c,b=N(a);a.T||!ea.test(b)?u(b):(u('<ins id="'+c.getHolderId()+'"></ins>'),a.i.setTimeout(function(){var d=a.i.document.getElementById(c.getHolderId());a.j=d;t(d,w({width:a.m+"px",height:a.s+"px"}));var e=X(a);a.a=e;d.appendChild(e);T(e,b)},0))}}function Y(a){a.K&&a.u&&(a.v=ia(a),z(a.u,"click",a.v));a.H&&(a.A=function(){return fa(a)},z(a.i,"resize",a.A))}
function Z(a){a.H&&a.A&&(A(a.i,"resize",a.A),a.A=null);a.v&&a.u&&(A(a.u,"click",a.v),a.v=null)}g=Q.prototype;g.F=function(a){var c=this.a;return!(!c||c.contentWindow!==a)};
g.G=function(){M.prototype.G.call(this);if(this.g)t(this.g,"display","inline-block"),Y(this);else{var a=this.c,c=this.i.document;if(a.getIsSyncLoading())ha(this);else{var b=this.M;if(this.c.isResponsive()&&b){var d=document.getElementById(b);if(d){var e={position:"absolute",display:"block",width:"100%",height:"100%",padding:"0",margin:"0",overflow:"hidden"};0===b.indexOf("revjet-tag")?t(d,e):this.B||(this.B=v("div",{o:{},style:e}),d.appendChild(this.B))}}if(b=W(this))if(this.c.isResponsive()){if(this.a)t(b,
"display","block");else{var f=x({name:"revjet-single-iframe","data-revjet-options":P(this)});this.a=f=v("iframe",{o:f,style:{display:"block",position:"absolute",top:"0",bottom:"0",left:"0",width:"100%",height:"100%",border:"0",padding:"0",margin:"0"}});a=N(this);b.appendChild(f);T(f,a)}Y(this)}else if(d=c.getElementById(a.getWrapperId()),e=c.getElementById(a.getHolderId()),"div"===this.S){d&&(y(d),this.a=this.j=this.g=null);a=N(this);if(a){f=c.createElement("div");f.innerHTML="L<div>"+B(a)+"</div>";
a=[];for(f=f.lastChild;f.firstChild;)a.push(f.removeChild(f.firstChild));f=a}else f=[];D(b,f,c)()}else{var k=1;if(c=this.H){k=V(this,!1);var m=U(this,k);k=m.scale;m=w({display:"block",width:"100%",height:m.height+"px"})}else m=w({display:"inline-block",width:this.m+"px",height:this.s+"px"});d?(t(d,m),this.g=d):this.g=v("ins",{o:{id:a.getWrapperId()},style:m});m.display="block";e?(t(e,m),this.j=e):this.j=v("ins",{o:{id:a.getHolderId()},style:m});this.a=X(this);c&&(a="scale("+k+")",this.a.style.webkitTransformOrigin=
"0 0",this.a.style.transformOrigin="0 0",this.a.style.webkitTransform=a,this.a.style.transform=a,this.a.style.backfaceVisibility="hidden");this.j.appendChild(this.a);this.K&&!this.u&&(a=O(this,"/~cdn/JS/03/3.4.3/x-button.28x28.png"),f=void 0===f?window.document:f,f=v("img",{o:{src:a},style:{margin:0,padding:0,position:"absolute",left:"auto",bottom:"auto",right:0,top:0,border:0,zIndex:999999,width:"18px",height:"18px",cursor:"pointer",overflow:"hidden",cssFloat:"none",webkitAppearance:"none"}},f),
t(f,{zIndex:989999,left:this.m-18+"px",right:"auto",pointerEvents:"auto"}),this.u=f,this.j.appendChild(f));if(!d||!e){for(this.g.appendChild(this.j);b.firstChild;)b.removeChild(b.firstChild);b.appendChild(this.g)}T(this.a,N(this));Y(this)}}}};function ia(a){return function(){a.c.hide()}}function W(a){var c=a.c,b=a.i.document;c=a.M||c.getContainerId();return a.B||b.getElementById(c)}
g.D=function(){M.prototype.D.call(this);Z(this);if(this.c.isResponsive()){var a=W(this);t(a,"display","none")}else this.g&&t(this.g,"display","none")};g.C=function(){M.prototype.C.call(this);Z(this);if(this.c.isResponsive()){var a=W(this);a&&y(a)}else this.a&&y(this.a);this.u=this.g=this.j=this.a=null};g.J=function(){return this.a?[this.a]:[]};Q.prototype.getFrames=Q.prototype.J;Q.prototype.destroyAd=Q.prototype.C;Q.prototype.hideAd=Q.prototype.D;Q.prototype.showAd=Q.prototype.G;REVJET_Tag.ModuleManager.getInstance().setLoaded("banner",Q);})();

